repos:
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.29.1
        hooks:
            -   id: pyupgrade
                args: [--py36-plus]

    -   repo: https://github.com/PyCQA/pylint
        rev: v2.10.2
        hooks:
            -   id: pylint

    -   repo: https://github.com/PyCQA/flake8
        rev: 3.9.2
        hooks:
            -   id: flake8
                additional_dependencies:
                    - flake8-broken-line==0.3.0
                    - flake8-quotes==3.3.1
